flags:
  highlighting-kate: { pcre-light: true }
packages:
  - '.'
  - location:
      git: https://github.com/myfreeweb/indieweb-algorithms.git
      commit: 3a70a6bee81dcb4c1b65a3081ff0c250c64f0fc6
    extra-dep: true
  - location:
      git: https://github.com/myfreeweb/hs-duktape.git
      commit: 1ab03a588dd38eb7e3a33502b941733bf810ddeb
    extra-dep: true
  - location:
      git: https://github.com/myfreeweb/pcre-heavy.git
      commit: 9873fb019873340b212780d12595c0f66ec88613
    extra-dep: true
  - location:
      git: https://github.com/myfreeweb/microformats2-parser.git
      commit: cdd16012a6d367c4256ba4585737b2b94ac60c42
    extra-dep: true
  - location:
      git: https://github.com/myfreeweb/gitson.git
      commit: 90c85dbf5fddd6fc4a84bcc1d491293e5e9414ec
    extra-dep: true
  - location:
      git: https://github.com/myfreeweb/http-link-header.git
      commit: ab530b746f7c1daf648ffbfd700340de2c91e12e
    extra-dep: true
  - location:
      git: https://github.com/myfreeweb/haskell-socket-activation.git
      commit: c67f50d80e4b83515e88672cbd689d4383710b23
    extra-dep: true
extra-deps:
  - git-embed-0.1.0
  - highlighting-kate-0.6.3
resolver: nightly-2016-12-16
