packages:
  - '.'
  - location: '../indieweb-algorithms'
    extra-dep: true
  - location: '../../../nikita-volkov/bytestring-tree-builder'
    extra-dep: true
extra-deps:
  - rapid-0.1.3
allow-newer: true
resolver: nightly-2018-07-08
